### ISSUE TITLE
Getting Yaw Information and Angukar.z field?

### ISSUE THREAD

**Issue by Rak-r** [adityakamath/optical_flow_ros#6]
Firstly, thanks for the great work.

Actually, I am developing something similar using PMW3901 for ground robot. I ahve calibrated the sensor for linear. x and linear.y speeds and verified for known straight distance, seems reasonable. Now, I am looking into how can I extract/generate the yaw information to make a complete twist message and pass on to the EKF.

I have tried doing some vector maths for a full 360 right drive, I find the direction using `math.atan2(vy, vx)` to get the current theta and then finding the change in theta named as `delta_theta`. After this I calculate the `angualr.z` using `delta_theta/delta_time`.  However, when I visualize the data in rviz it seems the robot going towards left while in actual it was a full 360 right drive. and do not represent the curve rather drifts.
 I verified with different method using steering feedback with which the robot goes to the right and seems to go in full circle. 
Below is method for the same. Could you provide any insight with this. Or is this even the right approach to get the yaw information. The sensor is mounted is same orientation as the The robot (Forward X (+), Left Y (+) ). One more thing the sensor is mounted on the left side of my robot with origin (x = +0.0, y = +0.36, z = +0.150) considering my base_link origin is at centre of the full robot chassis. @adityakamath 
`  

       def calculate_theta(self, vy,vx):
                                                  
        v_magnitude = math.sqrt((vx)**2 + (vy)**2)                                             # Find the magnitude for the velocity
        current_theta = math.atan2(vy,vx)                                                 # Find the current rotating angle of the robot
       
        
        print(f'Current Theta :{current_theta}')
        d_theta = current_theta - self.old_theta                                           # calculate change in rotating  angle
                             
        self.old_theta = current_theta                                                     # Update the rotating angle
        
        
        return  d_theta
`

**Finding angular velocity and updating other variables**

`
       

     self.delta_theta = self.calculate_theta(self.vy_ms, self.vx_ms)       
        self.v_angular = self.delta_theta/self.dt                                         # find angular velocity from (delta_theta/dt)
        
        dx = (self.vx_ms*math.cos(self.theta))*self.dt
        dy = (self.vx_ms*math.sin(self.theta))*self.dt
        self.x += dx
        self.y += dy
        self.theta += self.delta_theta
`

**Comment by izeemeen** [comment]
@Rak-r, Hi! 
Can you help me with this problem:
I launch: "ros2 launch optical_flow_ros optical_flow_launch.py" and get this error:

[INFO] [launch]: All log files can be found below /home/user/.ros/log/2024-07-09-12-35-42-041072-raspberrypi-321083
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [optical_flow_publisher-1]: process started with pid [321104]
[optical_flow_publisher-1] Traceback (most recent call last):
[optical_flow_publisher-1]   File "/home/user/ros2_iron/install/optical_flow_ros/lib/optical_flow_ros/optical_flow_publisher", line 33, in <module>
[optical_flow_publisher-1]     sys.exit(load_entry_point('optical-flow-ros', 'console_scripts', 'optical_flow_publisher')())
[optical_flow_publisher-1]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[optical_flow_publisher-1]   File "/home/user/ros2_iron/install/optical_flow_ros/lib/optical_flow_ros/optical_flow_publisher", line 25, in importlib_load_entry_point
[optical_flow_publisher-1]     return next(matches).load()
[optical_flow_publisher-1]            ^^^^^^^^^^^^^^^^^^^^
[optical_flow_publisher-1]   File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
[optical_flow_publisher-1]     module = import_module(match.group('module'))
[optical_flow_publisher-1]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[optical_flow_publisher-1]   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
[optical_flow_publisher-1]     return _bootstrap._gcd_import(name[level:], package, level)
[optical_flow_publisher-1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[optical_flow_publisher-1]   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
[optical_flow_publisher-1]   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
[optical_flow_publisher-1]   File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
[optical_flow_publisher-1]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[optical_flow_publisher-1]   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
[optical_flow_publisher-1]   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
[optical_flow_publisher-1]   File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
[optical_flow_publisher-1] ModuleNotFoundError: No module named 'optical_flow'
[ERROR] [optical_flow_publisher-1]: process has died [pid 321104, exit code 1, cmd '/home/user/ros2_iron/install/optical_flow_ros/lib/optical_flow_ros/optical_flow_publisher --ros-args -r __node:=optical_flow -r __ns:=/ --params-file /home/user/ros2_iron/install/optical_flow_ros/share/optical_flow_ros/config/sensor_params.yaml -r odom:=flow_odom'].


How can I resolve it?

**Comment by Rak-r** [comment]
Could you show me your package structure? and package.xml and Cmakelists.txt @izeemeen

**Comment by izeemeen** [comment]
@Rak-r, thanks for response!
I don't have Cmakelists.txt, package.xml looks like:

<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>optical_flow_ros</name>
  <version>0.0.0</version>
  <description>ROS 2 package for PMW3901 and PAA5100 (short-range) Optical Flow Sensors</description>
  <maintainer email="adityakamath@live.com">Aditya Kamath</maintainer>
  <license>Apache License 2.0</license>
    
  <depend>rclpy</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>lifecycle_msgs</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>


What I need to do?

**Comment by Rak-r** [comment]
I haven't used this repo for my work. Instead I created my own sensor framework which can just talk via serial. But seems I found the bug. There is the issue in the repo's `setup.py`.  If you look closely in the console scripts, the package name is `optical_flow` and but the actual name is  'optical_flow_ros`, that's why it cannot find the package created. You just need to replace the `setup.py` with the one I am sharing below and try a fresh build and source the workspace. Then, try to run the launch file or node.  

I always try to build the package using `ament_cmake`, much better to handle unless it specifcially something to do with python. You can even run python nodes in the cmake package, which is a good flexibility of ros2. @izeemeen 

If interested: https://roboticsbackend.com/ros2-package-for-both-python-and-cpp-nodes/ 

 `
    
        import os
        from glob import glob
        from setuptools import setup
        
        package_name = 'optical_flow_ros'
        
        setup(
            name=package_name,
            version='0.0.0',
            packages=[package_name],
            data_files=[
                ('share/ament_index/resource_index/packages',
                    ['resource/' + package_name]),
                ('share/' + package_name, ['package.xml']),
                (os.path.join('share', package_name, 'launch'), glob('launch/*.py')),
                (os.path.join('share', package_name, 'config'), glob('config/*.yaml')),
            ],
            install_requires=['setuptools', 'pmw3901', 'numpy'],
            zip_safe=True,
            maintainer='Aditya Kamath',
            maintainer_email='adityakamath@live.com',
            description='ROS 2 package for PMW3901 and PAA5100 (short-range) Optical Flow Sensors',
            license='Apache License 2.0',
            tests_require=['pytest'],
            
            entry_points={
                'console_scripts': [
                    'optical_flow_publisher = optical_flow_ros.optical_flow_publisher:main',          
                    'optical_flow_node = optical_flow_ros.optical_flow_node:main',
                ],
            },
        )

`

**Comment by izeemeen** [comment]
@Rak-r,  thanks for response!

I resolve this problem!!!
But now I have this one: 

[INFO] [launch]: All log files can be found below /home/user/.ros/log/2024-07-09-14-17-48-259922-raspberrypi-3234
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [optical_flow_publisher-1]: process started with pid [3252]
[optical_flow_publisher-1] [INFO] [1720531069.134756948] [optical_flow]: Initialized
[ERROR] [launch_ros.actions.lifecycle_node]: Failed to make transition 'TRANSITION_CONFIGURE' for LifecycleNode '/optical_flow'

Do you know what this is?

**Comment by Rak-r** [comment]
Have a search for it. This might be due to some way the launch file created. Instead try creating a simple launch file and remove the lifecycle stuff for a moment from the node and existing launch file. Then, when you can run that it might better to try lifecycle out.

**Comment by izeemeen** [comment]
@Rak-r 
Could this be due to the fact that the camera is not connected or connected incorrectly?
Or would there be a different type of error?
Thanks in advance for your answer

**Comment by Rak-r** [comment]
Ah!, I believe it is failing at configuration, so that might be the case. For debugging, try to remove the configuration event from the launch by commenting it out from both ld.action and emit event. Try running, it will do run which tells its having issue in config.

**Comment by izeemeen** [comment]
Thank You, @Rak-r!
I'll try this solution!

**Comment by adityakamath** [comment]
Thanks for finding the bug @Rak-r, I've pushed the fix to setup.py. 

And you are right, ament_cmake is definitely the better way. I'm only using ament_python here as I ended up using the same template for multiple sensors. When I have the time, I will update my initial template and all corresponding packages with ament_cmake. 

Also, apologies for not being able to make time for your original issue. I hope you have found a workaround, I am still quite busy to make time for it. Good luck!

**Comment by adityakamath** [comment]
@Rak-r closing this issue since its been open for a while. As far as I know, there is no direct way of getting precise orientation unless you use an additional sensor - a second Optical Flow sensor or even an IMU and combine the data from both sensors.
